# This is a basic workflow to help you get started with Actions

name: Build and Push Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create-image:
    name: Build Image and Push
    needs: build
    uses: cant-code/github-workflows/.github/workflows/docker-push.yml@main
    with:
      DOCKER_TAG: damnationcantcode/parking-space-ui
      ARTIFACT_NAME: ecommerce-ui
      ARTIFACT_PATH: target
    secrets: inherit